language: csharp
notifications:
  email: false

matrix:
  include:
    - dotnet: 1.0.0-preview2-1-003177
      mono: none
      env: DOTNETCORE=1
      install:
        - dotnet restore
      script:
        - dotnet build
        - dotnet test test/Multiformats.Base.Tests
    - mono: latest

branches:
  only:
    - master

cache:
  - directories:
    - ./packages
