language: csharp
notifications:
  email: false

install:
  - git config --global core.autocrlf input
  - git submodule update --init --recursive

matrix:
  include:
    - dotnet: 1.0.0-preview2-003131
      mono: none
      env: DOTNETCORE=1
      install:
        - dotnet restore -v Minimal
      script:
        - dotnet build -r ubuntu.16.04-x64 -c Release src/Multiformats.Base
        - dotnet test test/Multiformats.Base.Tests
    - mono: latest

branches:
  only:
    - master

cache:
  - directories:
    - ./packages
    - ./lib
