language: csharp

notifications:
  email:
    on_success: change
    on_failure: always

branches:
  only:
    - master

cache:
  - directories:
    - ./packages

install:
  - git config --global core.autocrlf input
  - git submodule update --init --recursive

matrix:
  fast_finish: true
  include:
    - os: osx
      osx_image: xcode7.3
      dotnet: 1.0.0-preview2-003131
      mono: none
      env: DOTNETCORE=1 OSX=1
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-003131
      mono: none
      env: DOTNETCORE=1 LINUX=1
    #- os: linux
    #  mono: latest
    #  sudo: false
    #- os: osx
    #  mono: latest

script:
  - if [ -n "${DOTNETCORE}" && -n "${OSX}" ]; then dotnet restore && dotnet build -r osx-x64 -f netstandard1.6 -c Release src/Multiformats.Base && dotnet test -r osx-x64 -f netcoreapp1.1 test/Multiformats.Base.Tests; fi
  - if [ -n "${DOTNETCORE}" && -n "${LINUX}" ]; then dotnet restore && dotnet build -r linux-x64 -f netstandard1.6 -c Release src/Multiformats.Base && dotnet test -r linux-x64 -f netcoreapp1.1 test/Multiformats.Base.Tests; fi
  #- if [ -z "${DOTNETCORE}" ]; then xbuild /p:Configuration=Release travis-mono-test.sln; fi
  #- if [ -z "${DOTNETCORE}" ]; then mono travis-mono-test/bin/Release/travis-mono-test.exe; fi
