version: 1.1.{build}
configuration: Release
platform: x64
init:
  - git config --global core.autocrlf input
#assembly_info:
#  patch: true
#  file: '**\AssemblyInfo.*'
#  assembly_version: '{version}'
#  assembly_file_version: '{version}'
#  assembly_informational_version: '{version}'
install:
  - git submodule update --init --recursive
before_build:
  - dotnet restore
build_script:
  - dotnet build "src\Multiformats.Base" -c %CONFIGURATION% --version-suffix %APPVEYOR_BUILD_NUMBER%
after_build:
  - dotnet pack "src\Multiformats.Base" -c %CONFIGURATION% --no-build --version-suffix %APPVEYOR_BUILD_NUMBER% -o artifacts
test: off
before_test:
  - nuget install OpenCover -Version 4.6.519
test_script:
  - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -returntargetcode -target:"dotnet" -targetargs:"test test\Multiformats.Tests -c %CONFIGURATION%" -filter:"+[Multiformats.Base]* -[Multiformats.Base.Benchmarks]* -[Multiformats.Base.Tests]*" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All -output:.\coverage.xml
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - pip install codecov
  - codecov -f ".\coverage.xml"
artifacts:
  - path: artifacts\**\*.*
cache:
  - '%USERPROFILE%\.nuget\packages'
  - .\packages
deploy:
  - provider: NuGet
    api_key:
      secure: WcDqU36pLPvA+s5D4N0VEsi7AZGewvf4croE/D3rh3F+iqiztq9w5gHbrhgoTNS9
    on:
      branch: master
      appveyor_repo_tag: true
  - provider: GitHub
    description: 'Release description'
    auth_token:
      secure: nsZHZ5nFBFP4fZoVUEeWeZKx7LUASVqCZ+JblTox+02RfTAOlANdFWeCqOwhu7pk
    artifact: /.*\.nupkg/            # upload all NuGet packages to release assets
    draft: false
    prerelease: false
    on:
      branch: master                 # release from master branch only
      appveyor_repo_tag: true