environment:
  PKG_VERSION: 1.1.0
version: ${PKG_VERSION}-{build}
configuration: Release
platform: x64

skip_commits:
  message: /travis/
  files:
    - '**/*.md'
    - LICENSE

skip_branch_with_pr: true

matrix:
  fast_finish: true

init:
  - git config --global core.autocrlf input
  - ps: $env:BUILD_VERSION = "$env:PKG_VERSION.$env:APPVEYOR_BUILD_NUMBER"
  - ps: |
      if ($env:APPVEYOR_REPO_BRANCH -eq "master") 
      {
          $env:NUGET_VERSION = "$env:PKG_VERSION"
      }
      else
      {
          $env:NUGET_VERSION = "$env:PKG_VERSION-beta$env:APPVEYOR_BUILD_NUMBER"
      }
  - ps: Update-AppveyorBuild -Version $env:BUILD_VERSION

install:
  - git submodule update --init --recursive

before_build:
  - appveyor-retry dotnet restore -v Minimal

build_script:
  - dotnet build "src\Multiformats.Base" -c %CONFIGURATION% --version-suffix %APPVEYOR_BUILD_NUMBER%

after_build:
  - dotnet pack "src\Multiformats.Base" -c %CONFIGURATION% --no-build --version-suffix %APPVEYOR_BUILD_NUMBER% -o artifacts

test: off

before_test:
  - nuget install OpenCover -Version 4.6.519 -OutputDirectory .\tools

test_script:
  - .\tools\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -returntargetcode -target:"%ProgramFiles%\dotnet\dotnet.exe" -targetargs:"test -r win-64 -f netcoreapp1.0 %APPVEYOR_BUILD_FOLDER%\test\Multiformats.Base.Tests -c %CONFIGURATION%" -filter:"+[Multiformats.Base]* -[Multiformats.Base.Benchmarks]* -[Multiformats.Base.Tests]*" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All -output:"%APPVEYOR_BUILD_FOLDER%\coverage.xml" -oldStyle

after_test:
  - ps: |
        $wc = New-Object 'System.Net.WebClient'
        $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit3/$($env:APPVEYOR_JOB_ID)", (Resolve-Path (.\TestResults.xml)))

on_success:
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - pip install codecov
  - codecov -f "%APPVEYOR_BUILD_FOLDER%\coverage.xml" -X gcov
  - appveyor PushArtifact "%APPVEYOR_BUILD_FOLDER%\artifacts\Multiformats.Base.%NUGET_VERSION%.nupkg"

artifacts:
  - path: artifacts\**\*.*

cache:
  - '%USERPROFILE%\.local'
  - '%USERPROFILE%\.nuget\packages'
  - '%LocalAppData%\NuGet\Cache'
  - '%LocalAppData%\Python'
  - '.\packages' -> '.\**\*.json'
  - '.\tools'
  - '\Python34'

nuget:
  account_feed: true

deploy:
  - provider: NuGet
    api_key:
      secure: WcDqU36pLPvA+s5D4N0VEsi7AZGewvf4croE/D3rh3F+iqiztq9w5gHbrhgoTNS9
    on:
      branch: master
      appveyor_repo_tag: true
  - provider: GitHub
    description: 'Release description'
    auth_token:
      secure: nsZHZ5nFBFP4fZoVUEeWeZKx7LUASVqCZ+JblTox+02RfTAOlANdFWeCqOwhu7pk
    artifact: /.*\.nupkg/            # upload all NuGet packages to release assets
    draft: false
    prerelease: false
    on:
      branch: master                 # release from master branch only
      appveyor_repo_tag: true